arch: amd64

branches:
  only: 
    - main

language: rust

dist: focal

os: linux

services:
  - docker

job:
  include:
    - name: focal-bcc-0.17
      env: BCC=0.17.0 FEATURES=v0_17_0 LLVM=9 KERNEL_VERSION=5.9 STATIC=true BUILD_DOCKER_IMAGE=false
    - name: focal-bcc-0.16
      env: BCC=0.16.0 FEATURES=v0_16_0 LLVM=9 KERNEL_VERSION=5.8 STATIC=true BUILD_DOCKER_IMAGE=false

  fast_finish: true

script:
  - build/run_new_kernel.sh
